### ISSUE TITLE
exemplo linguagem de m'aquina falta um bit

### ISSUE THREAD

**Issue by rafaelcorsi** [Insper/22a-Z01.1#55]
https://github.com/Insper/Z01.1/blob/b63597c966b164ef3cfa50b60cc1892afbd0212a/docs-src/Teoria-Linguagem-de-Maquina.md?plain=1#L50

Oi @renan-tr  estava usando esse material e percebi que falta um bit nesse exemplo! Deveriam ser 18 e so' tem 17!

abs

**Comment by rafaelcorsi** [comment]
deveria ser ` 1 000 0 000010 0 010 000`

**Comment by renan-tr** [comment]
Feito
